Feature/#42-GETandPUTusers
Stacking-Up/data-service pull request #49
Opened 2022-03-30 18:08 UTC by jesvarzam

## Tareas realizadas:
* Revisión de los endpoint GET /api/v1/users y GET /api/v1/users/{userId} para comprobar que devuelven toda la información necesaria para el perfil de un usuario.
* Implementación del endpoint PUT /api/v1/users/{userId}
* Testeo del endpoint PUT /api/v1/users/{userId}

## Problemas encontrados:
* Al no conocer el funcionamiento de la implementación del authToken y de algunos aspectos de privilegios de usuarios, tuve algunos problemas al inicio de la tarea al probar el endpoint PUT /api/v1/spaces/{spaceId}. 
**Solución**: pregunté a un compañero, en concreto Tomás, para saber si me podía ayudar a resolver el error, resolviéndolo con éxito finalmente.

2022-03-31 09:33 UTC, alesancor1 requested changes
**1) ERROR DE VALIDACIÓN:**

De la forma en la que está planteada la validación, un usuario no puede modificar su propio perfil, me explico:

```javascript
//userControllerService #62-65
 if (decoded.role !== 'ADMIN' && (decoded.role === 'USER' || parseInt(decoded.userId) !== parseInt(userToBeUpdated.id))) {
        res.status(403).send('Forbidden');
        return;
      }
```

En este código, un usuario administrador puede sin problema modificar el usuario, pues la primera parte de la condición `decoded.role!=='ADMIN'` evaluaría false.

Sin embargo, un usuario no puede modificar su perfil debido a que la condición siempre evalúa true para cualquier usuario. La validación que has utilizado es la que se utiliza en los espacios, que verifica que un usuario deba estar verificado. Ese no es el caso aquí.

La solución es modificar la condición de manera que cualquier usuario pueda modificar su perfil siempre y cuando coincida con el ID de su sesión, de la siguiente manera:

```javascript
      if (decoded.role !== 'ADMIN' && parseInt(decoded.userId) !== parseInt(userToBeUpdated.id)) {
        res.status(403).send('Forbidden');
        return;
      }
```

**2) ERROR 500 - ENUMERADO**

Al tratar de actualizar un usuario con un valor del enumerado `sex` inválido, se produce el siguiente error:
```
Argument sex: Provided value 'Aa' of type String on prisma.updateOneUser is not a enumTypes.
→ Possible values: Sex.MALE, Sex.FEMALE, Sex.OTHER


    at Object.validate (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:38614:20)
    at PrismaClient._executeRequest (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:40702:17)
    at consumer (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:40646:23)
    at C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:40650:76
    at runInChildSpan (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:39891:12)
    at C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:40650:20
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at PrismaClient._request (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:40649:86)      
    at C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:37277:25
    at _callback (C:\Users\Alex\Desktop\Alex\ETSII\ISPP\data-service\node_modules\@prisma\client\runtime\index.js:37041:52) {
  clientVersion: '3.11.1'
}
```

Para solucionar este problema se necesaria la implementación de una validación para el enumerado `sex`.

** 3) FECHA INVÁLIDA SE PONE A NULL: **

Al introducir una fecha que no sigue el formato de fecha, es decir que es inválida, el usuario se actualiza correctamente y se pone a null en la base de datos:

![image](https://user-images.githubusercontent.com/72552837/161025971-cad957ab-e7cb-4e63-8fa4-ac68ef07ba64.png)
![image](https://user-images.githubusercontent.com/72552837/161026092-4b036c68-3788-4c77-8cbf-e620b56802bb.png)

La solución a este problema es implementar una validación de fecha, al igual que en otros endpoints.

2022-04-01 13:58 UTC, tomgalbar commented
He estado revisando el código y hay varias cosas que debes cambiar e introducir @jesvarzam:

### 1) ERROR EN EL BODY SWAGGER: 
En swagger en el body de la petición del put de user has puesto como atributo el id y no es necesario, es mejor quitarlo para evitar problemas. Deberás modificar el archivo oas-doc-yaml, eliminando en la parte de los components schemas las líneas 1468, 1472, 1473, 1474.

![image](https://user-images.githubusercontent.com/72520181/161236832-f7992c1a-21df-48d0-9ef7-5f525feae923.png)
![image](https://user-images.githubusercontent.com/72520181/161238008-2ec4f056-0b2b-40e3-b235-2b6e6b4a24d5.png)

### 2) ERROR CON LA CONDICION 403 FORBIDDEN:
Te he comentado antes que el id de un objeto nunca va a ser necesario pasarlo en el body de un post, por tanto el objeto que te venga de frontend no va a tener un campo id, solo los atributos. Es por ello, que en el apartado 1 de @alesancor1 que te mencionaba que esa condición estaba mal y tenías que modificarla tampoco te va a funcionar lo que el te comento al haber eliminado el id del body de swagger. Por tanto, y lo más correcto que tendrías que hacer, sería comprobar antes de la condición de forbbiden que el userId está definido y es un número (la condición que tienes en las líneas 67-70 ponerla justo antes del forbidden). Tras eso, tendrías que modificar la condición del forbidden de la siguiente forma:
```javascript
//userControllerService #62-65
if (decoded.role !== 'ADMIN' && parseInt(decoded.userId) !== parseInt(userId)) {
    res.status(403).send('Forbidden');
    return;
}
```
Con eso ya debería funcionar todo bien.

### 3) RESTRICCIONES ATRIBUTOS:
Antes de hacer el update para guardar en base de datos los atributos nuevos del usuario deberás comprobar cada uno para asegurar que no se guarde información inválida o inconsistente. A continuación detallo algunas de las validaciones necesarias (algunas de ellas ya comentados por @alesancor1 en su comentario anterior), las cuales puedes realizar fijándote en alguna de las validaciones de mi función `checkSpaceValidity` (utilizada en el endpoint post/put de spaces):

- [ ] Atributo "name" y "surname" deben ser de mínimo 3 caracteres de longitud
- [ ] Atributo "birthDate" debes asegurarte que sea una fecha y que no sea superior al día actual en el que se introduce (es decir, no se puede poner un cumpleaños de un día futuro, no tendría sentido)
- [ ] Atributo "sex" debes asegurarte que se introduce uno de los posibles valores del enumerado, de lo contrario, debe producirse un error al validarse. 
- [ ] Atributo "idCard" debes asegurarte que sigue el formato del DNI, teniendo en cuenta también que la letra se calcula en función de los números.
- [ ] Atributo "phoneNumber" debes asegurarte que solo se introducen números que sigan el formato "+34 XXXXXXXXX" donde las X son números. Por ejemplo "+34 666666666" es válido, sin embargo "+34666666666" no debería ser válido.

### 4) ERROR AL ACTUALIZAR USUARIO CON SUS RELACIONES
Cuando haces la actualización del usuario estás intentando actualizar también sus relaciones con otras tablas. Por ejemplo, intentas actualizar la relación Auth, eso nunca va a funcionar ya que lo que te mandan son únicamente los atributos básicos del objeto (y la imagen). Por tanto, cuando haces `userToBeUpdated.auth` siempre va a ser undefined (y lo mismo ocurre con el resto exceptuando imagen que ahora te comentaré). Es decir, no debes intentar actualizar esos campos, ya que la actualización de esos campos se realiza desde otros endpoints, tu endpoint únicamente debe actualizar la información básica del usuario. Por tanto cuando haces el update únicamente debes incluir: `name, surname, birthDate, sex, idCard, phoneNumber, location, avatar `. 

Para updatear la imagen deberías hacerlo de la siguiente manera:
```javascript
let queryUpdateUser = {
  where: {
    id: parseInt(userId)
  },
  data: {
    name: userToBeUpdated.name,
    surname: userToBeUpdated.surname,
    birthDate: userToBeUpdated.birthDate ? new Date(userToBeUpdated.birthDate) : null,
    sex: userToBeUpdated.sex ? userToBeUpdated.sex : null,
    idCard: userToBeUpdated.idCard ? userToBeUpdated.idCard : null,
    phoneNumber: userToBeUpdated.phoneNumber ? userToBeUpdated.phoneNumber : null,
    location: userToBeUpdated.location ? userToBeUpdated.location : null,
    avatar: {
      delete: await prisma.user.findUnique({where: {id: parseInt(userId)}, include: { avatar: true } }).then(user => user.avatar) ? true : false,
    }
  }
}

if(userToBeUpdated.avatar) {
  queryUpdateUser.data.avatar.create = { image: Buffer.from(userToBeUpdated.avatar, 'base64'), mimetype: userToBeUpdated.avatar.indexOf('/9j/') === 0 ? 'image/jpeg' : 'image/png' }
}

await prisma.user.update(queryUpdateUser).then(() => { 
```
El resto del código a partir de esa última línea adjuntada es igual que las que ya tienes.

2022-04-02 10:14 UTC, jesvarzam commented
Todos los cambios han sido revisados y commiteados.

2022-04-02 14:14 UTC, alesancor1 approved these changes

2022-04-02 14:17 UTC, alesancor1 commented
Apruebo los cambios, todo está correcto. Lo único a destacar es que al mandar el campo `sex` vacío (no definido), se produce un warning dado que ningún valor del enum coincide:

```bash
warn: [{"message":"Wrong data in the body of the request. ","error":[{"code":"ENUM_MISMATCH","params":[""],"message":"No enum match for: ","path":"#/sex"}],"content":{"name":"fffffff","surname":"bbbbb","birthDate":"2022-04-02T14:10:06.585Z","sex":"","idCard":"","phoneNumber":"","location":""}}]
```

2022-04-02 14:19 UTC, tomgalbar approved these changes
Al ser el warning mencionado por @alesancor1 debido al swagger no existe problema con ello. Apruebo los cambios.

2022-04-02 14:19 UTC, merged